# @Time    : 2024/08/20 16:18:20
# @Author  : phantom
# @Project : Zerotier
# @FileName: docker-compose.yml
version: '3.0'
services:
    ztncui:
        container_name: zerotier-planet
        restart: always
        environment:
            - MYADDR=
            - MYDOMAIN=
            - HTTP_PORT=3000
            - HTTPS_PORT=3443
            - ZTNCUI_PASSWD=
            - NODE_ENV=production
            - HTTP_ALL_INTERFACES=true
        ports:
            - '13000:3000'
            - '13443:3443'
            - '19993:9993'
            - '19993:9993/udp'
            - '13180:3180'
        volumes:
            - './zerotier-one:/var/lib/zerotier-one'
            - './ztncui/etc:/opt/key-networks/ztncui/etc'
        image: registry.cn-shanghai.aliyuncs.com/logandev/zerotier-ztncui:latest

networks:
    hostnet:
        external: true
        name: host